In [11]:
import torch
import numpy as np
from torch.autograd import Variable

In [5]:
# numpy与tensor的对转
np_data = np.arange(6).reshape((2, 3))
print(np_data)

torch_data = torch.from_numpy(np_data)
print(torch_data)

re_np_data = torch_data.numpy()
print(re_np_data)

[[0 1 2]
 [3 4 5]]
tensor([[0, 1, 2],
        [3, 4, 5]])
[[0 1 2]
 [3 4 5]]


In [9]:
# tensor操作方法
data = [[-1, -2], [1, 2]]
tensor = torch.FloatTensor(data)

print(tensor.abs())
print(tensor.sin())
print(torch.mm(tensor, tensor)) # matrix multiplication

tensor([[1., 2.],
        [1., 2.]])
tensor([[-0.8415, -0.9093],
        [ 0.8415,  0.9093]])
tensor([[-1., -2.],
        [ 1.,  2.]])


In [23]:
# variable
tensor = torch.FloatTensor([[1, 2], [3, 4]])
v = Variable(tensor, requires_grad=True)
print(v.data)

t_out = torch.mean(v ** 3)
t_out.backward()

print(v.grad)

tensor([[1., 2.],
        [3., 4.]])
tensor(25., grad_fn=<MeanBackward0>)
tensor([[ 0.7500,  3.0000],
        [ 6.7500, 12.0000]])
