### numpy张量计算

In [1]:
import numpy as np

In [2]:

## 算术运算
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x + y)  # 加法
print(x - y)  # 减法
print(x * y)  # 乘法
print(x / y)  # 除法
print(x ** 2)  # 平方
print(np.sqrt(x))  # 平方根

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[1.         1.41421356 1.73205081]


In [3]:

## 广播
x = np.array([1,2,3])
print(x * 2)

y = np.array([[1,2],[3,4],[5,6]])
z = np.array([1,1])
print(y + z)  

[2 4 6]
[[2 3]
 [4 5]
 [6 7]]


In [4]:

## 降维
x = np.array([[1,2],[3,4],[5,6]])
print(x.sum())  # 所有元素的和
y = x.flatten()  # 将矩阵展平为一维数组
print(y)
print(y[np.array([0,2,4])])  # 访问展平后的元素

21
[1 2 3 4 5 6]
[1 3 5]


In [5]:

## 多维数组
x = np.array([[1,2],[3,4],[5,6]])
print(x.shape)  # 输出数组的形状
print(np.ndim(x)) # 输出数组的维数

(3, 2)
2


In [7]:

## 矩阵乘法
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = np.dot(A, B)  # 矩阵点乘
#_ 或者使用 @ 运算符
D = A @ B

print(C)
print(D)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
