# 张量操作

## 概念环节

### 1) 张量的定义
- 张量（Tensor）是一个**多维数组**。  
- 通常将 `n` 维数组称为 `n` 阶张量。

### 2) 常见的张量类型
- **0 阶张量**：标量（Scalar）
- **1 阶张量**：向量（Vector）
- **2 阶张量**：矩阵（Matrix）
- **3 阶及以上**：高阶张量（Higher-order Tensor）

### 3) 张量的数据结构
张量主要由两部分组成：
- **数据（Data）**：张量中的具体元素值
- **形状（Shape）**：各维度大小，用于描述张量结构

> 本质上，张量可以理解为“具有特定索引/取值方式的数组”。

### 4) 张量取值的直观理解
可将一维数据按维度信息逐层划分为子数组，例如：
$$
\begin{bmatrix} 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \end{bmatrix}  
\rightarrow 
\begin{bmatrix}1 & 2 & 3 & 4 \\5 & 6 & 7 & 8\end{bmatrix}
\rightarrow 
\begin{bmatrix}1 & 2 \\3 & 4\end{bmatrix} \begin{bmatrix}5 & 6 \\7 & 8\end{bmatrix}(把它想象成两个2阶方阵叠在一起)
$$


In [3]:
import torch

### 一、张量的创建

In [4]:
# 1. 从列表创建
t1 = torch.tensor([[1, 2], [3, 4]])
t1


tensor([[1, 2],
        [3, 4]])

In [5]:
# 2. 使用内置函数创建
t2 = torch.arange(0,12)
t2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
# 3. 使用随机数创建
t3 = torch.rand(2, 3) #/ 生成一个2行3列的随机张量
t3

tensor([[0.3241, 0.9009, 0.4272],
        [0.6387, 0.9438, 0.2709]])

### 二、张量的变换

In [7]:
# 1.reshape方法
t4 = t2.reshape(3, 4) #/ 将t2重塑为3行4列的张量
t5 = t2.reshape(2, 3, 2) #/ 将t2重塑为3阶张量
t4,t5

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[[ 0,  1],
          [ 2,  3],
          [ 4,  5]],
 
         [[ 6,  7],
          [ 8,  9],
          [10, 11]]]))

In [8]:
# 2.transpose方法
t6 = t4.transpose(0, 1) #/ 转置t4
t6

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

### 三、张量的运算

In [9]:
# 1. 逐元素运算
t7 = t4 + 10 #/ 每个元素加10
t8 = t4 * 2 #/ 每个元素乘以2
t7,t8 

(tensor([[10, 11, 12, 13],
         [14, 15, 16, 17],
         [18, 19, 20, 21]]),
 tensor([[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]]))